/*


*/
#ifndef CONSTANTES

    #define CONSTANTES

    #define TAILLE_BLOC 34

    #define NBRE_BLOCS_LARGEUR 12
    #define NBRE_BLOCS_HAUTEUR 12

    #define LARGEUR_FENETRE TAILLE_BLOC * NBRE_BLOCS_LARGEUR //408
    #define HAUTEUR_FENETRE TAILLE_BLOC * NBRE_BLOCS_HAUTEUR //408

    enum{HAUT, BAS, GAUCHE, DROITE};
    enum{VIDE, MUR, CAISSE, CAISSE_OK, MARIO, OBJECTIF};

#endif // CONSTANTES

